spring.application.name=tax-server
# 데이터베이스 연결 정보
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정 (테이블 구조 자동 확인)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true